HOSTS:
  ubuntu-server-14.04-amd64:
    roles:
      - master
    platform: ubuntu-14.04-amd64
    box: puppetlabs/ubuntu-14.04-64-nocm
    box_url: https://vagrantcloud.com/puppetlabs/ubuntu-14.04-64-nocm
    vagrant_memsize: 3096
    hypervisor: vagrant
CONFIG:
  log_level: debug
  type: foss
